import {z} from "zod";


//generate bill schema

export const generateBillSchema = z.object({
    patientId:z.string().min(1,"Patient Id is required"),
    appointmentId:z.string().optional(),
    items:z.array(z.object({
        description:z.string().min(1,"Description is required"),
        quantity:z.number().int().min(1,"Quantity must be at least 1"),
        unitPrice:z.number().positive("Unit price must be positive number"),
        discount:z.number().min(0).default(0),
        total:z.number().positive("Total must be positive")
    })),
    tax:z.number().min(0).default(0),
    notes:z.string().max(500,"Notes cannot exceed 500 characters").optional(),
    generatedBy:z.string().min(1,"Generated by is required")

})


//update Bill schema
export const updateBillSchema=z.object({
     items:z.array(z.object({
        description:z.string().min(1,"Description is required"),
        quantity:z.number().int().min(1,"Quantity must be at least 1"),
        unitPrice:z.number().positive("Unit price must be positive number"),
        discount:z.number().min(0).default(0),
        total:z.number().positive("Total must be positive")
    })).optional(),
    tax:z.number().min(0).default(0),
    status:z.enum(['UNPAID','PAID','PARTIALLY_PAID','CANCELLED','REFUNDED']),
    notes:z.string().max(500,"Notes cannot exceed 500 characters").optional(),
})

//get Bills query schema 
export const getBillQuerySchema= z.object({
    page:z.string().optional().transform(Number).default("1"),
    limit:z.string().optional().transform(Number).limit("10"),
    patientId:z.string().optional(),
    status:z.enum(['UNPAID','PAID','PARTIALLY_PAID','CANCELLED','REFUNDED']),
    fromDate:z.string().datetime().optional(),
    toDate:z.string().datetime().optional(),
    search:z.string().optional()
})